### ISSUE TITLE
Not loading at all (possibly problem w/ API)

### ISSUE THREAD

**Issue by scottdonaldson** [kaicataldo/cumulus#4] opened 2015-05-24 14:37 UTC
Getting the following error in console:

```javascript
Uncaught TypeError: Cannot read property 'address_components' of undefined
```

And a totally blank screen. Not sure if the API is down or if they changed something that's incompatible with how it's being parsed, but I'm guessing the problem is one of those two.

**Comment by kaicataldo** [comment] 2015-05-24 14:45
Sounds like the Google Reverse Geolocation call is failing. I'd like to get around to building some fallback options/manual refresh button when the call fails, but what happens when you uninstall/reinstall the extension?

**Comment by kaicataldo** [comment] 2015-05-24 14:47
Also, do you have v 2.5.6?

**Comment by scottdonaldson** [comment] 2015-05-24 14:48
No change for me (uninstalled, reinstalled, restarted Chrome). And yup, it had automatically updated to 2.5.6.

**Comment by kaicataldo** [comment] 2015-05-24 14:51
Ah! Restarted my own machine and reinstalled and got the same error. Will look into it - thanks!

**Comment by kaicataldo** [comment] 2015-05-24 15:11
Weird...I was able to recreate the issue by uninstalling, restarting my machine, and reinstalling. But after loading up the extension in Developer Mode, it seems to be working just fine, and I can no longer recreate the issue with the version in the Chrome Store either. Any thoughts what might be causing the issue? It seems like it could be one of four things to me:
* Some syncing issues between the front-end script and the asynchronous calls in the background script (that pulls the data)
* AJAX data call is failing
* The data being stored in localStorage is momentarily unaccessable
* Chrome bug

**Comment by scottdonaldson** [comment] 2015-05-24 20:47
Not sure — all I can see is that the parsed `localStorage.resp2` should have a `results` array of length > 0, but for me is just an empty array.

**Comment by yurrriq** [comment] 2015-05-24 22:23
FWIW I've had weird issues like this caused by running AdBlock, Ghostery, et al.

**Comment by yurrriq** [comment] 2015-05-24 22:25
See also: http://www.catb.org/jargon/html/H/heisenbug.html

**Comment by kaicataldo** [comment] 2015-05-25 02:26
Thanks Eric. I'm still having trouble recreating this again. Any chance that's what is going on with you, Scott?

**Comment by scottdonaldson** [comment] 2015-05-25 14:43
Nope, not running either of those.

**Comment by kaicataldo** [comment] 2015-05-26 15:37
Scott - any chance you could uninstall the extension, clear your localStorage, and start with a clean slate? If that fixes it, I think I know what the problem is and can start working on a fix.

**Comment by scottdonaldson** [comment] 2015-05-26 18:17
I was just going to do this and I noticed that it's working again (with no additional work on my part). The weird thing is that I had given it a blue background, and it is back to the default black. But otherwise, it's showing weather data like normal and has no console messages, so I guess we're good?

One thing possibly to note is that this happened while I was out of town and I'm now back in NYC. Not sure if that would have anything to do with it.

**Comment by kaicataldo** [comment] 2015-05-26 18:26
Huh, that's so strange. If that's the case I wonder if it was some kind of error with the geolocation API at your location, making it unable to make the data calls (you were in the country, yeah? Sounds silly, but I I don't think it would successfully parse the data internationally)...Also strange that that background color changed. I guess I'll close this, but thanks for letting me know. 

I want to do another pass at it for a v3 that would hopefully catch these kinds of things, including switching from localStorage to the Chrome Extension storage API, better error handling and fallback options (manual refresh button if the call is unsuccessful), and a color picker for custom colors!

**Closed by kaicataldo** 2015-05-26 18:26 UTC
